language: java

jdk: openjdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

services: docker

branches:
  only: master

before_install:
  - chmod +x mvnw
  
script:
  # BUILD
  - ./mvnw package -B

# GET NAME
  - PRJ_GROUP=$(mvn project.artifactId -q | grep "groupId:" | awk '{print $2}')
  - PRJ_NAME=$(mvn project.artifactId)
  - PRJ_VERSION=$(project.artifactId)

  - echo "## PROJECT_GROUP - ${PRJ_GROUP}"
  - echo "## PROJECT_NAME - ${PRJ_NAME}"
  - echo "## PROJECT_VERSION - ${PRJ_VERSION}"

  #- PRJ_JAR=${PRJ_NAME}-${PRJ_VERSION}.jar
  - PRJ_JAR=standard-1.0.0.jar

  # DOCKER BUILD
  - docker build -t nwms.standard:latest --build-arg JAR_FILE=target/${PRJ_JAR} ./

  # PUSH TO DOCKER HUB
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  - docker tag nwms.standard:latest cain0605/nwms.standard:latest
  - docker tag nwms.standard:latest cain0605/nwms.standard:${TRAVIS_JOB_NUMBER}

  - docker push cain0605/nwms.standard:latest
  - docker push cain0605/nwms.standard:${TRAVIS_JOB_NUMBER}
  - docker push cain0605/nwms.standard
  
after_success:
  - mvn clean test jacoco:report coveralls:report
  
notifications:
  slack:
    rooms:
      - cain0605:uT682ndCB9pOlZOTRX6wI0oV#management