language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    
before_install:
  - chmod +x mvnw
  
script: "./mvnw test -B"

after_success:
  - mvn clean test jacoco:report coveralls:report
  
notifications:
  slack:
    rooms:
      - cain0605:uT682ndCB9pOlZOTRX6wI0oV#management  