# ===================================================================
# Spring boot database config
# ===================================================================
spring:
  datasource:
    url: jdbc:h2:mem:nwms;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    data: classpath:biz.sql,classpath:cd.sql,classpath:cust.sql,classpath:loc.sql,classpath:sku.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false