-- SD_SKU ==================================================================================================================
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080258','HDCR','HDCR','원*이앤지','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080259','HDCR','HDCR','카*베네(핫컵)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080260','HDCR','HDCR','원*성당','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080261','HDCR','HDCR','테*로사2도','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080262','HDCR','HDCR','롤*로이스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080263','HDCR','HDCR','둘*스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080264','HDCR','HDCR','씨*시나몬카푸치노','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080265','HDCR','HDCR','카*마고핫초코','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080266','HDCR','HDCR','넥*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080267','HDCR','HDCR','피*이아이','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080268','HDCR','HDCR','파*바게뜨아다지오','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080269','HDCR','HDCR','혼*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080270','HDCR','HDCR','르*삼성','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080271','HDCR','HDCR','비*이메이린','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080272','HDCR','HDCR','신*촌베이커리','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080273','HDCR','HDCR','디*이에프','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080274','HDCR','HDCR','인*니티','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080275','HDCR','HDCR','닛*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080276','HDCR','HDCR','브*지헤어살롱','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080277','HDCR','HDCR','온*베이비아울','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080278','HDCR','HDCR','씨*원두라떼(중국TSL)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080279','HDCR','HDCR','씨*캬라멜향마끼야또(중국TSL)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080280','HDCR','HDCR','나*바이네르','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080281','HDCR','HDCR','씨*초코카페라떼(중국TSL)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080282','HDCR','HDCR','씨*밀크카페라떼(중국TSL)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080283','HDCR','HDCR','씨*한라봉유자차(중국TSL)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080284','HDCR','HDCR','공*한옥마을','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080285','HDCR','HDCR','(*복사용금지)CU달콤핫쵸코(수정)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080286','HDCR','HDCR','씨*88블랙커피','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080287','HDCR','HDCR','루*스데토러스화이트','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080288','HDCR','HDCR','루*스데토러스블랙','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080225','HDCR','HDCR','베*핏다이어트업커피','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080226','HDCR','HDCR','베*핏다이어트업유자','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080227','HDCR','HDCR','티*콘소메스프홀더컵','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080228','HDCR','HDCR','티*허브스프홀더컵','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080229','HDCR','HDCR','담*호두아몬드율무홀더컵','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080230','HDCR','HDCR','씨*원두라떼중국','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080231','HDCR','HDCR','B*E','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080232','HDCR','HDCR','말*커피','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080233','HDCR','HDCR','구*(사용금지)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080234','HDCR','HDCR','y*ca','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080235','HDCR','HDCR','고*바','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080236','HDCR','HDCR','씨*캬라멜향마끼야또(러시아)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080237','HDCR','HDCR','(*용금지)CU원두라떼','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080238','HDCR','HDCR','씨*블랙커피','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080239','HDCR','HDCR','커*빈(일본)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080240','HDCR','HDCR','태*오설록','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080241','HDCR','HDCR','웨*베아트리체','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080242','HDCR','HDCR','남*프렌치카페(노랑)홀더컵','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080243','HDCR','HDCR','이*한세상(화이트)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080244','HDCR','HDCR','이*한세상(브라운)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080245','HDCR','HDCR','계*밥상','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080246','HDCR','HDCR','푸*아이웨어','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080247','HDCR','HDCR','레*머그','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080248','HDCR','HDCR','오*이크','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080249','HDCR','HDCR','알*라','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080250','HDCR','HDCR','동*화재그린라이트(2종혼입)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080251','HDCR','HDCR','루*드컵(강아지)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080252','HDCR','HDCR','루*드컵(토끼)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080253','HDCR','HDCR','우*아웃백','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080254','HDCR','HDCR','베*컴코리아','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080255','HDCR','HDCR','이*헤어커커','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080256','HDCR','HDCR','카*베네(베이글)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080194','HDCR','HDCR','씨*프렌치바닐라(사할린)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080195','HDCR','HDCR','씨*원두라떼(사할린)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080196','HDCR','HDCR','씨*프렌치바닐라(블라디)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080197','HDCR','HDCR','씨*캬라멜향마끼야또(블라디)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080198','HDCR','HDCR','씨*화이트쵸코캬라멜카푸치노(블라디)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080199','HDCR','HDCR','씨*핫쵸코(블라디)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080200','HDCR','HDCR','씨*모카카푸치노(블라디)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080201','HDCR','HDCR','윈*리닉','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080202','HDCR','HDCR','씨*밀크라떼(블라디)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080203','HDCR','HDCR','벨*토','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080204','HDCR','HDCR','처*처럼','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080205','HDCR','HDCR','차*유어스콜롬비아아메리카노','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080206','HDCR','HDCR','파*앤벌룬코리아라바','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080207','HDCR','HDCR','세*쌍화차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080208','HDCR','HDCR','코*아','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080209','HDCR','HDCR','투*이로스팅','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080210','HDCR','HDCR','커*머신종이컵8온스(CU20211)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080211','HDCR','HDCR','카*리비','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080212','HDCR','HDCR','온*듀','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080213','HDCR','HDCR','온*버치','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080214','HDCR','HDCR','온*아울','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080215','HDCR','HDCR','무*백컵(온스)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080216','HDCR','HDCR','파*스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080217','HDCR','HDCR','에*로','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080218','HDCR','HDCR','기*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080219','HDCR','HDCR','일*코리아','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080220','HDCR','HDCR','오*다','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080221','HDCR','HDCR','씨*블루베리향카푸치노(블라디)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080222','HDCR','HDCR','메*라이프푸켓','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080223','HDCR','HDCR','더*스트클래스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100023','HDCR','HDCR','카*몰리나리','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100024','HDCR','HDCR','테*로사4도','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100025','HDCR','HDCR','일*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100026','HDCR','HDCR','골*클래스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100027','HDCR','HDCR','뺑*프랑스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100028','HDCR','HDCR','해*치','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100029','HDCR','HDCR','크*마커피','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100030','HDCR','HDCR','크*제버거','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100031','HDCR','HDCR','컴*고커피','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100032','HDCR','HDCR','대*기본(블랙)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100033','HDCR','HDCR','대*기본(레드)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100034','HDCR','HDCR','대*기본(갈색)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100035','HDCR','HDCR','카*루미','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100036','HDCR','HDCR','기*컵건평','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100037','HDCR','HDCR','웰*토리','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100038','HDCR','HDCR','현*하이스코','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100039','HDCR','HDCR','네*카페','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100040','HDCR','HDCR','카*펠리치따','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100041','HDCR','HDCR','일*코리아','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100042','HDCR','HDCR','스*스낵','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100043','HDCR','HDCR','카*테리아(아이제제)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100044','HDCR','HDCR','네*카페화이트','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100045','HDCR','HDCR','라*짜','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100046','HDCR','HDCR','코*아커피(시즌)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100047','HDCR','HDCR','아*제제기본','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100048','HDCR','HDCR','라*바','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100049','HDCR','HDCR','더*피하우스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100050','HDCR','HDCR','루*블랙','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100051','HDCR','HDCR','뜨*슈아','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100052','HDCR','HDCR','페*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100053','HDCR','HDCR','프*치키스녹색','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080289','HDCR','HDCR','상*원','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080290','HDCR','HDCR','커*코트8oz','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080291','HDCR','HDCR','요*진','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080292','HDCR','HDCR','작*명V','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080293','HDCR','HDCR','위*윈(160713)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080294','HDCR','HDCR','바*리국민떡볶이','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080295','HDCR','HDCR','이*턴드림','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080296','HDCR','HDCR','대*르네프랑케','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080297','HDCR','HDCR','코*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080298','HDCR','HDCR','꽃*커피컵','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080299','HDCR','HDCR','춘*휴먼드림','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100001','HDCR','HDCR','업*운다이너','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100002','HDCR','HDCR','무*백컵','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100003','HDCR','HDCR','프*치키스적색','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100004','HDCR','HDCR','프*치키스청색','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100005','HDCR','HDCR','올*브돈까스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100006','HDCR','HDCR','테*로사(쑥색)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100007','HDCR','HDCR','휘*스파크','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100008','HDCR','HDCR','달*리','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100009','HDCR','HDCR','샌*데이','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100010','HDCR','HDCR','U*C','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100011','HDCR','HDCR','샌*앤푸드','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100012','HDCR','HDCR','무*띠','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100013','HDCR','HDCR','카*테리아(자연드림)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100014','HDCR','HDCR','워*파크블루케니언','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100015','HDCR','HDCR','커*하우스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100016','HDCR','HDCR','마*핀','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100017','HDCR','HDCR','레*망고','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100018','HDCR','HDCR','카*루이스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100019','HDCR','HDCR','코*아커피-1000','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100020','HDCR','HDCR','B*Q','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00100021','HDCR','HDCR','코*티암','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080257','HDCR','HDCR','엠*스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080098','HDCR','HDCR','미*터커피','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080036','HDCR','HDCR','차*유어스핫쵸코','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080037','HDCR','HDCR','차*유어스블루마운틴','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080038','HDCR','HDCR','차*밀크카페라떼','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080039','HDCR','HDCR','차*유어스캬라멜향마끼아또','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080040','HDCR','HDCR','C*원두라떼','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080041','HDCR','HDCR','신*진꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080042','HDCR','HDCR','신*유자차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080043','HDCR','HDCR','신*생강꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080044','HDCR','HDCR','신*모과꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080045','HDCR','HDCR','신*생강꿀차(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080046','HDCR','HDCR','신*모과꿀차(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080047','HDCR','HDCR','신*홍삼꿀차(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080048','HDCR','HDCR','신*한라봉유자차(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080049','HDCR','HDCR','차*6년근홍삼꿀차8oz','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080050','HDCR','HDCR','차*유어스한라봉유자차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080051','HDCR','HDCR','차*유어스생강꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080052','HDCR','HDCR','세*한라봉유자차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080053','HDCR','HDCR','세*생강꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080054','HDCR','HDCR','세*헛개꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080055','HDCR','HDCR','미*스톱한라봉유자차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080056','HDCR','HDCR','미*스톱생강꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080057','HDCR','HDCR','프*치키스기본','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080058','HDCR','HDCR','프*치키스녹색','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080059','HDCR','HDCR','프*치키스청색','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080060','HDCR','HDCR','한*차(대국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080061','HDCR','HDCR','네*카페(화이트)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080062','HDCR','HDCR','네*카페(블랙)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080063','HDCR','HDCR','네*카페(오렌지)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080064','HDCR','HDCR','네*카페알레그리아','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080065','HDCR','HDCR','무*백컵','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080066','HDCR','HDCR','커*빈','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080006','HDCR','HDCR','씨*블루마운틴','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080007','HDCR','HDCR','씨*화이트쵸코캬라멜카푸치노','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080008','HDCR','HDCR','씨*밀크라떼','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080009','HDCR','HDCR','씨*프렌치바닐라','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080010','HDCR','HDCR','씨*헤이즐넛향원두','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080011','HDCR','HDCR','씨*캬라멜향마끼야또','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080012','HDCR','HDCR','씨*블루베리향카푸치노','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080013','HDCR','HDCR','씨*블루베리향핫초코','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080014','HDCR','HDCR','씨*초코카페라떼','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080015','HDCR','HDCR','씨*원두라떼','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080016','HDCR','HDCR','씨*핫초코(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080017','HDCR','HDCR','씨*캬라멜향마끼야또(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080018','HDCR','HDCR','씨*블루마운틴(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080019','HDCR','HDCR','씨*블루베리향핫초코(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080020','HDCR','HDCR','씨*화이트초코카랴멜향카푸치노(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080021','HDCR','HDCR','씨*헤이즐넛향원두(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080022','HDCR','HDCR','씨*프렌치바닐라(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080023','HDCR','HDCR','씨*밀크카페라떼(러시아)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080024','HDCR','HDCR','씨*모카카푸치노(러시아)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080025','HDCR','HDCR','씨*핫초코(러시아)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080026','HDCR','HDCR','씨*프렌치바닐라(러시아)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080027','HDCR','HDCR','씨*화이트초코캬랴멜향카푸치노(러시아)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080028','HDCR','HDCR','씨*블루베리향카푸치노(러시아)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080029','HDCR','HDCR','씨*한라봉유자차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080030','HDCR','HDCR','씨*생강꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080031','HDCR','HDCR','씨*모과꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080032','HDCR','HDCR','C*달콤핫초코','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080033','HDCR','HDCR','C*생강꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080034','HDCR','HDCR','C*한라봉유자차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080035','HDCR','HDCR','차*유어스모카카푸치노','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050036','HDCR','HDCR','포*트페이퍼휘슬러(단면)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050037','HDCR','HDCR','고*바','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050038','HDCR','HDCR','소*트랩(빙그레)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050039','HDCR','HDCR','태*오설록크리스마스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070001','HDCR','HDCR','씨*원두헤이즐넛향','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070002','HDCR','HDCR','씨*프렌치바닐라','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070003','HDCR','HDCR','씨*헤이즐넛향','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070004','HDCR','HDCR','G*25모카커피믹스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070005','HDCR','HDCR','라*짜','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070006','HDCR','HDCR','샤*망꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070007','HDCR','HDCR','남*나라(로고)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070008','HDCR','HDCR','C*헤이즐넛향','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070009','HDCR','HDCR','샤*망생강꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070010','HDCR','HDCR','씨*모카커피믹스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070011','HDCR','HDCR','블*원오미자','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070012','HDCR','HDCR','블*원블루베리','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070013','HDCR','HDCR','신*학원','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070014','HDCR','HDCR','씨*헤이즐넛향(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070015','HDCR','HDCR','씨*프렌치바닐라(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070016','HDCR','HDCR','씨*모카커피믹스(중국)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070017','HDCR','HDCR','샤*망솔잎꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070018','HDCR','HDCR','샤*망궁중차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070019','HDCR','HDCR','샤*망차전마차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070020','HDCR','HDCR','컵*즉석미역국','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070021','HDCR','HDCR','씨*리얼믹스커피','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00070022','HDCR','HDCR','씨*리얼블랙커피','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080001','HDCR','HDCR','맥*웰아메리카노','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080002','HDCR','HDCR','맥*웰헤이즐넛','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080003','HDCR','HDCR','기*컵건평','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080004','HDCR','HDCR','씨*모카카푸치노','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080005','HDCR','HDCR','씨*핫쵸코','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050004','HDCR','HDCR','아*디오','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050005','HDCR','HDCR','본*라또1도','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050006','HDCR','HDCR','마*베트','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050007','HDCR','HDCR','뽀*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050008','HDCR','HDCR','리*플아이스크림','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050009','HDCR','HDCR','돌*프레드','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050010','HDCR','HDCR','카*드아떼','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050011','HDCR','HDCR','프*젤','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050012','HDCR','HDCR','펀*팜','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050013','HDCR','HDCR','루*카토','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050014','HDCR','HDCR','젤*트리','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050015','HDCR','HDCR','휘*러','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050016','HDCR','HDCR','더*페','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050017','HDCR','HDCR','캐*키드슨','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050018','HDCR','HDCR','(*결)모모스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050019','HDCR','HDCR','태*오설록','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050020','HDCR','HDCR','블*바니','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050021','HDCR','HDCR','컨*턴제주호텔','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050022','HDCR','HDCR','카*더이은(양면)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050023','HDCR','HDCR','티*위니','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050024','HDCR','HDCR','엠*이커피','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050025','HDCR','HDCR','노*루','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050026','HDCR','HDCR','디*다트','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050027','HDCR','HDCR','주*피','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050028','HDCR','HDCR','레*머그','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050029','HDCR','HDCR','모*이야기(블랙번즈)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050030','HDCR','HDCR','태*당(양면)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050031','HDCR','HDCR','롯*스위트월드','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050032','HDCR','HDCR','한*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050033','HDCR','HDCR','태*이니스프리','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050034','HDCR','HDCR','태*크리스마스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080224','HDCR','HDCR','커*머신종이컵8온스(13년)28424','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080163','HDCR','HDCR','뽀*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080164','HDCR','HDCR','아*시니카제이콥스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080165','HDCR','HDCR','맥*티커피','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080166','HDCR','HDCR','크*스마스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080167','HDCR','HDCR','밝*세상안과','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080168','HDCR','HDCR','딱*치는닭강정','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080169','HDCR','HDCR','웅*바바봉다리(10*100)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080170','HDCR','HDCR','(*결)동일미래핫초코','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080171','HDCR','HDCR','디*페인아메리카노','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080172','HDCR','HDCR','박*뷰티랩','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080173','HDCR','HDCR','잡*드','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080174','HDCR','HDCR','호*아몬드율무차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080175','HDCR','HDCR','씨*진꿀차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080176','HDCR','HDCR','쌍*차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080177','HDCR','HDCR','레*차','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080178','HDCR','HDCR','석*토스트','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080179','HDCR','HDCR','(*결)지엠컴','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080180','HDCR','HDCR','달*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080181','HDCR','HDCR','성*순복음교회','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080182','HDCR','HDCR','레*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080183','HDCR','HDCR','(*결)랜드로바','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080184','HDCR','HDCR','씨*캬라멜향마끼야또(사할린)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080185','HDCR','HDCR','씨*블루베리향카푸치노(사할린)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080186','HDCR','HDCR','씨*핫초코(사할린)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080187','HDCR','HDCR','씨*화이트초코캬라멜향카푸치노(사할린)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080188','HDCR','HDCR','씨*블루베리향핫초코(블라디)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080189','HDCR','HDCR','씨*모카카푸치노(사할린)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080190','HDCR','HDCR','씨*밀크카페라떼(사할린)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080191','HDCR','HDCR','씨*블루베리향핫초코(사할린)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080192','HDCR','HDCR','식*바나나라떼','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080193','HDCR','HDCR','식*메론라떼','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080131','HDCR','HDCR','(*결)크라프트','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080132','HDCR','HDCR','할*스블랜드','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080133','HDCR','HDCR','진*전원교회','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080134','HDCR','HDCR','(*결)벤츠','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080135','HDCR','HDCR','커*매니아(녹색)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080136','HDCR','HDCR','커*매니아(하늘색)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080137','HDCR','HDCR','(*결)라이온스클럽','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080138','HDCR','HDCR','(*결)태창금속산업','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080139','HDCR','HDCR','튼*영어','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080140','HDCR','HDCR','몽*마키','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080141','HDCR','HDCR','오*다(전통문화)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080142','HDCR','HDCR','오*다(원산지)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080143','HDCR','HDCR','오*다(전통문양)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080144','HDCR','HDCR','오*다(한글)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080145','HDCR','HDCR','오*다(전통음식)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080146','HDCR','HDCR','오*다(혼입)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080147','HDCR','HDCR','커*브러리','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080148','HDCR','HDCR','(*결)갓텐코리아(스시)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080149','HDCR','HDCR','커*커퍼','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080150','HDCR','HDCR','바*리커피컵','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080151','HDCR','HDCR','트*코드','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080152','HDCR','HDCR','제*앤','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080153','HDCR','HDCR','휘*러','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080154','HDCR','HDCR','맥*티카페비엔나','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080155','HDCR','HDCR','맥*티카페카라멜','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080156','HDCR','HDCR','맥*티카푸치노시나몬','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080157','HDCR','HDCR','맥*티카푸치노프렌치바닐라','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080158','HDCR','HDCR','세*포션(블랙)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080159','HDCR','HDCR','세*포션(스위트)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080160','HDCR','HDCR','세*포션(헤이즐넛)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080161','HDCR','HDCR','디*메디컬허브','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080162','HDCR','HDCR','양*공원','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080099','HDCR','HDCR','라*나골프클럽','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080100','HDCR','HDCR','베*건스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080101','HDCR','HDCR','아*(연두)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080102','HDCR','HDCR','렉*스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080103','HDCR','HDCR','풀*셋','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080104','HDCR','HDCR','우*대학교','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080105','HDCR','HDCR','루*녹색','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080106','HDCR','HDCR','루*보라색','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080107','HDCR','HDCR','루*하늘색','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080108','HDCR','HDCR','루*주황색','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080109','HDCR','HDCR','디*콜릿','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080110','HDCR','HDCR','자*시티','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080111','HDCR','HDCR','웅*바바바닐라블랜드','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080112','HDCR','HDCR','웅*바바바리스타블랜드','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080113','HDCR','HDCR','(*결)데레쿠니','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080114','HDCR','HDCR','세*모카핫초코','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080115','HDCR','HDCR','우*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080116','HDCR','HDCR','웅*바바커피','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080117','HDCR','HDCR','소*비발디','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080118','HDCR','HDCR','따*모','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080119','HDCR','HDCR','세*버디클럽','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080120','HDCR','HDCR','러*에이지','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080121','HDCR','HDCR','워*힐호텔','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080122','HDCR','HDCR','모*닭강정','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080123','HDCR','HDCR','통*닭강정','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080124','HDCR','HDCR','통*가마강정','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080125','HDCR','HDCR','카*온기본레드','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080126','HDCR','HDCR','지*산국립공원','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080127','HDCR','HDCR','웅*바바CU시즌','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080128','HDCR','HDCR','커*머신종이컵CU','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080129','HDCR','HDCR','라*헤어','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080130','HDCR','HDCR','요*자','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080067','HDCR','HDCR','파*바게뜨','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080068','HDCR','HDCR','달*리','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080069','HDCR','HDCR','버*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080070','HDCR','HDCR','애*타임','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080071','HDCR','HDCR','무*띠신형','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080072','HDCR','HDCR','북*페','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080073','HDCR','HDCR','아*마니','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080074','HDCR','HDCR','엠*리오아르마니','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080075','HDCR','HDCR','메*지핫컵(수출용)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080076','HDCR','HDCR','아*박스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080077','HDCR','HDCR','라*짜(신형)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080078','HDCR','HDCR','제*모직','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080079','HDCR','HDCR','구*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080080','HDCR','HDCR','신*촌레스토랑','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080081','HDCR','HDCR','s*.jone(에스티존)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080082','HDCR','HDCR','탐*탐스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080083','HDCR','HDCR','로*스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080084','HDCR','HDCR','드*기','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080085','HDCR','HDCR','농*보노스프','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080086','HDCR','HDCR','세*프레도(레드)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080087','HDCR','HDCR','세*프레도(화이트)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080088','HDCR','HDCR','대*기본(블랙)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080089','HDCR','HDCR','대*기본(레드)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080090','HDCR','HDCR','대*기본(갈색)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080091','HDCR','HDCR','웰*토리','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080092','HDCR','HDCR','b*gemot(베헤모트)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080093','HDCR','HDCR','지*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080094','HDCR','HDCR','더*루','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080095','HDCR','HDCR','호*티롤(무주덕유산리조트)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080096','HDCR','HDCR','홈*러스아카데미','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00080097','HDCR','HDCR','야*','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050035','HDCR','HDCR','구*토커피(양면)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00030001','HDCR','HDCR','구*띠모(사용금지)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00040001','HDCR','HDCR','스*벅스','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00040002','HDCR','HDCR','스*벅스티바나3종','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00040003','HDCR','HDCR','스*벅스리저브','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00040004','HDCR','HDCR','스*벅스크리스마스HOL-500','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050001','HDCR','HDCR','오*록','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050002','HDCR','HDCR','무*백컵(아이스)','None',0,0,'None',now(),'admin',now(),'admin');
INSERT INTO SD_SKU (SKU,CLIENT,BIZ,SKUNM,UOM,WT,STDUNTPC,TAXTP,RGSDE,RGSUSR,UPDDE,UPDUSR)
VALUES ('GDSI00050003','HDCR','HDCR','한*식품','None',0,0,'None',now(),'admin',now(),'admin');
